export const filterData = [
  // {
  //   title: 'Všetky',
  //   id: 'all',
  //   color: '#a855f7',
  // },
  {
    title: "Our choice",
    id: "our-choice",
    classNm: "jobs-inpts",
    name: "category",
    value: "our-choice",
    labelFor: "our-choice",
    textColor: "text-orange-500",
    bgColor: "hover:bg-orange-500",
    borderColor: "border-orange-500",
    bgColorTool: "bg-accent-pink",
  },
  {
    title: "Analytics",
    id: "analytics",
    classNm: "jobs-inpts",
    name: "category",
    value: "analytics",
    labelFor: "analytics",
    textColor: "text-tag-color-2",
    bgColor: "hover:bg-tag-color-2",
    borderColor: "border-tag-color-2",
    bgColorTool: "bg-tag-color-2",
  },

  {
    title: "BI / DATA",
    id: "bi-data",
    classNm: "jobs-inpts",
    name: "category",
    value: "bi-data",
    labelFor: "bi-data",
    textColor: "text-tag-color-3",
    bgColor: "hover:bg-tag-color-3",
    borderColor: "border-tag-color-3",
    bgColorTool: "bg-primary",
  },
  {
    title: "Recruitment - ATS",
    id: "recruitment-ats",
    classNm: "jobs-inpts",
    name: "category",
    value: "recruitment-ats",
    labelFor: "recruitment-ats",
    textColor: "text-tag-color-4",
    bgColor: "hover:bg-tag-color-4",
    borderColor: "border-tag-color-4",
    bgColorTool: "bg-tag-color-4",
  },
  {
    title: "Recruitment - Testing",
    id: "recruitment-testing",
    classNm: "jobs-inpts",
    name: "category",
    value: "recruitment-testing",
    labelFor: "recruitment-testing",
    textColor: "text-tag-color-5",
    bgColor: "hover:bg-tag-color-5",
    borderColor: "border-tag-color-5",
    bgColorTool: "bg-tag-color-5",
  },
  {
    title: "Automation - RPA",
    id: "automation-rpa",
    classNm: "jobs-inpts",
    name: "category",
    value: "automation-rpa",
    labelFor: "automation-rpa",
    textColor: "text-tag-color-6",
    bgColor: "hover:bg-tag-color-6",
    borderColor: "border-tag-color-6",
    bgColorTool: "bg-tag-color-6",
  },
  {
    title: "Communication",
    id: "communication",
    classNm: "jobs-inpts",
    name: "category",
    value: "communication",
    labelFor: "communication",
    textColor: "text-tag-color-7",
    bgColor: "hover:bg-tag-color-7",
    borderColor: "border-tag-color-7",
    bgColorTool: "bg-tag-color-7",
  },
  {
    title: "Design & graphics",
    id: "design-graphics",
    classNm: "jobs-inpts",
    name: "category",
    value: "design-graphics",
    labelFor: "design-graphics",
    textColor: "text-tag-color-8",
    bgColor: "hover:bg-tag-color-8",
    borderColor: "border-tag-color-8",
    bgColorTool: "bg-tag-color-8",
  },
  {
    title: "Management",
    id: "management",
    classNm: "jobs-inpts",
    name: "category",
    value: "management",
    labelFor: "management",
    textColor: "text-tag-color-1",
    bgColor: "hover:bg-tag-color-1",
    borderColor: "border-tag-color-1",
    bgColorTool: "bg-tag-color-1",
  },
  {
    title: "Marketing",
    id: "marketing",
    classNm: "jobs-inpts",
    name: "category",
    value: "marketing",
    labelFor: "marketing",
    textColor: "text-tag-color-2",
    bgColor: "hover:bg-tag-color-2",
    borderColor: "border-tag-color-2",
    bgColorTool: "bg-tag-color-2",
  },
  {
    title: "Sales",
    id: "sales",
    classNm: "jobs-inpts",
    name: "category",
    value: "sales",
    labelFor: "sales",
    textColor: "text-tag-color-3",
    bgColor: "hover:bg-tag-color-3",
    borderColor: "border-tag-color-3",
    bgColorTool: "bg-tag-color-3",
  },
  {
    title: "Scheduling",
    id: "scheduling",
    classNm: "jobs-inpts",
    name: "category",
    value: "scheduling",
    labelFor: "scheduling",
    textColor: "text-tag-color-4",
    bgColor: "hover:bg-tag-color-4",
    borderColor: "border-tag-color-4",
    bgColorTool: "bg-tag-color-4",
  },
  {
    title: "Social Media",
    id: "social-media",
    classNm: "jobs-inpts",
    name: "category",
    value: "social-media",
    labelFor: "social-media",
    textColor: "text-tag-color-5",
    bgColor: "hover:bg-tag-color-5",
    borderColor: "border-tag-color-5",
    bgColorTool: "bg-tag-color-5",
  },
  {
    title: "Security",
    id: "security",
    classNm: "jobs-inpts",
    name: "category",
    value: "security",
    labelFor: "security",
    textColor: "text-tag-color-6",
    bgColor: "hover:bg-tag-color-6",
    borderColor: "border-tag-color-6",
    bgColorTool: "bg-tag-color-6",
  },
  {
    title: "Technology",
    id: "technology",
    classNm: "jobs-inpts",
    name: "category",
    value: "technology",
    labelFor: "technology",
    textColor: "text-tag-color-7",
    bgColor: "hover:bg-tag-color-7",
    borderColor: "border-tag-color-7",
    bgColorTool: "bg-tag-color-7",
  },
  {
    title: "Time Tracking",
    id: "time-tracking",
    classNm: "jobs-inpts",
    name: "category",
    value: "time-tracking",
    labelFor: "time-tracking",
    textColor: "text-tag-color-8",
    bgColor: "hover:bg-tag-color-8",
    borderColor: "border-tag-color-8",
    bgColorTool: "bg-tag-color-8",
  },
  {
    title: "Video Conference",
    id: "video-conference",
    classNm: "jobs-inpts",
    name: "category",
    value: "video-conference",
    labelFor: "video-conference",
    textColor: "text-tag-color-1",
    bgColor: "hover:bg-tag-color-1",
    borderColor: "border-tag-color-1",
    bgColorTool: "bg-tag-color-1",
  },
  {
    title: "VC investments",
    id: "vc-investments",
    classNm: "jobs-inpts",
    name: "category",
    value: "vc-investments",
    labelFor: "vc-investments",
    textColor: "text-tag-color-2",
    bgColor: "hover:bg-tag-color-2",
    borderColor: "border-tag-color-2",
    bgColorTool: "bg-tag-color-2",
  },
  {
    title: "Workspace",
    id: "workspace",
    classNm: "jobs-inpts",
    name: "category",
    value: "workspace",
    labelFor: "workspace",
    textColor: "text-tag-color-3",
    bgColor: "hover:bg-tag-color-3",
    borderColor: "border-tag-color-3",
    bgColorTool: "bg-tag-color-3",
  },
  {
    title: "More in one",
    id: "more-in-one",
    classNm: "jobs-inpts",
    name: "category",
    value: "more-in-one",
    labelFor: "more-in-one",
    textColor: "text-tag-color-4",
    bgColor: "hover:bg-tag-color-4",
    borderColor: "border-tag-color-4",
    bgColorTool: "bg-tag-color-4",
  },
];
