export const contactCardInfo = [
  {
    title: 'LUXEMBOURG',
    tag: 'LUXEMBOURG',
    bg: 'bg-bgLux',
    coworking: 'The Office (Coworking)',
    address1: '29 Blvrd Grnd-Duchesse Charlotte,',
    address2: '1331 Luxembourg',
    link: 'https://goo.gl/maps/x1tYVhEXPA9Ecsz76',
  },
  {
    title: 'PRAGUE',
    tag: 'CZECHIA',
    bg: 'bg-bgPra',
    coworking: 'Impact Hub (Coworking)',
    address1: 'Drtinova 557/10,',
    address2: '150 00 Praha 5, Czechia',
    link: 'https://goo.gl/maps/5Ax4UoY6rnut75gc6',
  },
  {
    title: 'KOŠICE',
    tag: 'SLOVAKIA',
    bg: 'bg-bgKe',
    coworking: 'Fabrika 48 (Coworking)',
    address1: 'Južná Trieda 48,',
    address2: '04001 Košice, Slovakia',
    link: 'https://goo.gl/maps/NedEFcHhEQBvFigt6',
  },
  {
    title: 'WARSAW',
    tag: 'POLAND',
    bg: 'bg-bgWar',
    coworking: 'Google Campus (Coworking)',
    address1: 'Plac Konesera 10,',
    address2: '03-736 Warszawa, Poland',
    link: 'https://goo.gl/maps/gwCUNo4ysNHcP52CA',
  },
  {
    title: 'BERLIN',
    tag: 'GERMANY',
    bg: 'bg-bgBer',
    coworking: 'WeWork (Coworking)',
    address1: 'Kemperplatz 1 Mitte D,',
    address2: '10785 Berlin, Germany',
    link: 'https://goo.gl/maps/N6mpLVoAXotznmZq7',
  },
  {
    title: 'DUBAI',
    tag: 'UAE',
    bg: 'bg-bgDub',
    coworking: 'WeWork (Coworking)',
    address1: 'The Offices 4, One Central',
    address2: 'Dubai, 00000 UAE',
    link: 'https://goo.gl/maps/gLhdcEAWbkacmXs98',
  },
];
